sudo: false

language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - npm i

script:
  - docker build -t dojot/dojot-module_tests -f ./tests/docker/DockerFile .
  - docker-compose -f ./tests/docker/docker-compose.yml up -d
  